package vnu.uet.volunteer_hub.volunteer_hub_backend.model.enums;

public enum NotificationType {
    REGISTRATION_SUBMITTED,
    REGISTRATION_CONFIRMED,
    REGISTRATION_REJECTED,
    COMPLETION_MARKED,
    EVENT_CREATED_PENDING,
    EVENT_APPROVED,
    EVENT_REJECTED,
    EVENT_UPDATED,
    NEW_POST,
    NEW_COMMENT,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    SYSTEM_ANNOUNCEMENT,
    DATA_EXPORT_READY
}
